## **TASK: 1(i)**

In [1]:
import numpy as np
def determinant(A):
    n = A.shape[0]
    if n == 1:
        return A[0, 0]
    else:
        det = 0
        for j in range(n):
            submatrix = np.delete(np.delete(A, 0, axis=0), j, axis=1)
            det += (-1) ** j * A[0, j] * determinant(submatrix)
        return det

a = np.array([[0, 1, -1,  7, 9],
              [2, -4, 9, -6, 8],
              [1, -2, 1,  6 ,8],
              [2, 4 , 6,  9, 10],
              [5, -3 ,9,  6, 5]],dtype=float)

determinant(a)

-3292.0

# **TASK: 1(ii)**
No,it is not possible to calculate the determinant of the 4x5 matrix as it is not a square matrix (not have same number of rows and columns) while the determinant is only possible for a square matrix (a matrix having same number of rows and columns).

##Task 2: Implement the LU Decomposition Algorithm manually for the matrix A = [[0, 1, -1],[2, -4, 9],[1, -2, 1]]. Make sure to show all the steps in your working:

In [2]:
import numpy as np
def LUdecomp(A):
    if determinant(A)==0:
      print("Matrix is Singular LU decomposition not possible")
      return None
    else:
     n = len(A)
     P = np.eye(n)
     L = np.eye(n)
     Lo=np.zeros(n)
     U = np.zeros(n)
     for k in range(0, n-1):
        max_index = k + np.argmax(np.abs(a[k:, k]))
        if max_index > k:
            A[[k, max_index]] = A[[max_index, k]]
            P[[k, max_index]] = P[[max_index, k]]
        for i in range(k+1, n):
                lam = A[i,k]/A[k,k]
                L[i,k] = lam
                A[i,k+1:n] = A[i,k+1:n] - lam*A[k,k+1:n]
                A[i,k] = 0

    U=np.triu(A)
    Lo=np.tril(A)
    print('LU decomposition of A is given by \n L=\n',np.matrix(L),'and \n U=\n',np.matrix(U),"by using permutation matrix \n P=\n",np.matrix(P),"by using Lower tri matrix using np \n Lo=\n",np.matrix(Lo))
    return
a = np.array([[0, 1, -1],
              [2, -4, 9],
              [1, -2, 1]],dtype=float)
LUdecomp(a)


LU decomposition of A is given by 
 L=
 [[1.  0.  0. ]
 [0.  1.  0. ]
 [0.5 0.  1. ]] and 
 U=
 [[ 2.  -4.   9. ]
 [ 0.   1.  -1. ]
 [ 0.   0.  -3.5]] by using permutation matrix 
 P=
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]] by using Lower tri matrix using np 
 Lo=
 [[ 2.   0.   0. ]
 [ 0.   1.   0. ]
 [ 0.   0.  -3.5]]


# TASK: 3

In [3]:
import numpy as np
from scipy.linalg import lu
A = np.array([[0, 1, -1], [2, -4, 9], [1, -2, 1]],dtype=float)
P, L, U = lu(A)
print("Permutation Matrix (P):\n", P)
print("Lower Triangular Matrix (L):\n", L)
print("Upper Triangular Matrix (U):\n", U)
lu=np.dot(L,U)
print("LU Product:\n",lu)
d=np.diag(U)
lo=np.diag(d)
print("Lower tri matrix:\n",lo)

Permutation Matrix (P):
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]
Lower Triangular Matrix (L):
 [[1.  0.  0. ]
 [0.  1.  0. ]
 [0.5 0.  1. ]]
Upper Triangular Matrix (U):
 [[ 2.  -4.   9. ]
 [ 0.   1.  -1. ]
 [ 0.   0.  -3.5]]
LU Product:
 [[ 2. -4.  9.]
 [ 0.  1. -1.]
 [ 1. -2.  1.]]
Lower tri matrix:
 [[ 2.   0.   0. ]
 [ 0.   1.   0. ]
 [ 0.   0.  -3.5]]


##**Task 4:**

In [6]:
import numpy as np
import numpy.linalg as LA
from tabulate import tabulate

def Gauss_Siedel(A, b, x, tol, N):

    k = 0
    data=[]
    converged = False
    for i in range(len(b)):
        if A[i,i] == 0:
            j = i + np.argmax(np.abs(A[i:, i]))
            A[[i, j]] = A[[j, i]]
            b[[i, j]] = b[[j, i]]

    while k <= N:
        k += 1
        x0 = x.copy()
        data.append([k,x0[0],x0[1],x0[2]])
        for i in range(len(b)):
            Sum = 0
            for j in range(len(b)):
                if j != i:
                    Sum += A[i,j] * x[j]
            x[i] = (1 / A[i,i]) * (b[i] - Sum)

        if LA.norm(x - x0) < tol:
            converged = True
            print(tabulate(data,headers=['Iter no','x1','x2',"x3"],tablefmt="github"))
            print('Converged! in',k,'th iterations')
            return None

    if not converged:
        print(tabulate(data,headers=['Iter no','x1','x2',"x3"],tablefmt="github"))
        print('Not converged, increase the # of iterations')

A=np.array([[8,8,3],[2,8,5],[3,5,10]],dtype=float)
b=np.array([[14],[5],[-8]],dtype=float)
N=10
tol=0.01

x=np.zeros_like(b)
Gauss_Siedel(A,b,x,tol,N)


|   Iter no |       x1 |       x2 |       x3 |
|-----------|----------|----------|----------|
|         1 | 0        | 0        |  0       |
|         2 | 1.75     | 0.1875   | -1.41875 |
|         3 | 2.09453  | 0.988086 | -1.9224  |
|         4 | 1.48281  | 1.4558   | -1.97274 |
|         5 | 1.03398  | 1.59947  | -1.90993 |
|         6 | 0.866754 | 1.60202  | -1.86103 |
|         7 | 0.845871 | 1.57668  | -1.8421  |
|         8 | 0.864109 | 1.56029  | -1.83938 |
|         9 | 0.87948  | 1.55474  | -1.84121 |
Converged! in 9 th iterations
